fundamental of tensorflow


In [1]:
import tensorflow as tf
print(tf.__version__)

2.5.0


In [2]:
# create first tensor tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [3]:
# check the number of dimensions of tensor
scalar.ndim

0

In [4]:
# create a vector
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10])>

In [5]:
# check the dimension of vector
vector.ndim

1

In [6]:
# create a matrix
matrix = tf.constant([[1,1],
                     [3,4]])

matrix
        

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 1],
       [3, 4]])>

In [7]:
# dimension
matrix.ndim

2

In [8]:
# create another matrix 
another_matrix = tf.constant([[10.0, 7.0],
                             [3.,2.],
                             [8.,9.]], dtype=tf.float16) # specify datatype with d type parameters

another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [9]:
# dimension of another matrix  ; you will see this is still two
another_matrix.ndim

2

In [10]:
# create a tensor
tensor = tf.constant([[[1,2,3],[4,5,6]],
                      [[7,7,9],[10,11,12]], 
                      [[13,14,15],[16,17,18]]])


In [11]:
tensor, tensor.ndim

(<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
 array([[[ 1,  2,  3],
         [ 4,  5,  6]],
 
        [[ 7,  7,  9],
         [10, 11, 12]],
 
        [[13, 14, 15],
         [16, 17, 18]]])>,
 3)

In [12]:
# dimension of tensor
tensor.ndim

3

#What we've created so far
    
    * Scalar - no dimension
    * Vector (value and direction) - one dimension
    * Matrix  - two dimension 
    * Tensor - n dimension
    
All are tensors having different dimensions
 

creating tensors with `tf.Variable`


In [13]:
tf.Variable

tensorflow.python.ops.variables.Variable

In [14]:
# changable vector and unchangeble vector
changable_vector = tf.Variable([10,7])
unchangable_vector = tf.constant([10,7])

changable_vector, unchangable_vector

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7])>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7])>)

In [15]:
changable_vector[0].assign(7)
changable_vector

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7])>

In [16]:
# Variable vs constant

In [17]:
# Create two random (but same) tensors
tensor_1 = tf.random.Generator.from_seed(2) # set seed for reproducibility
tensor_1 = tensor_1.normal(shape=(3,2))
tensor_2 = tf.random.Generator.from_seed(2)
tensor_2 = tensor_2.uniform(shape=(3,2))

tensor_1, tensor_2, tensor_1 == tensor_2 

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.1012345 , -0.2744976 ],
        [ 1.4204658 ,  1.2609464 ],
        [-0.43640924, -1.9633987 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[0.95810425, 0.55623317],
        [0.16466296, 0.13445711],
        [0.13229859, 0.5348098 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[False, False],
        [False, False],
        [False, False]])>)

In [18]:
### Shuffle the order of element of tensor - ! Important

In [19]:
not_shuffled = tf.constant([[10,7],
                           [3,4],
                           [2,5]])
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]])>

In [20]:
tf.random.set_seed(42)

tf.random.shuffle(not_shuffled,seed=42) # this gives unshuffeled matrix

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]])>

Exercise

In [21]:
# creating tensors with zeros and ones
tf.zeros([3,4])

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

In [22]:
tf.ones([10,7])

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [23]:
# turn numpy arrays in to tensors
import numpy as np
numpy_A = np.arange(1,25, dtype=np.int32)  # create numpy array
numpy_A

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [24]:
A = tf. constant(numpy_A)
B = tf.constant(numpy_A, shape=(6,4))

A,B

(<tf.Tensor: shape=(24,), dtype=int32, numpy=
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24])>,
 <tf.Tensor: shape=(6, 4), dtype=int32, numpy=
 array([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12],
        [13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]])>)

In [25]:
B.ndim # I am correct in this case

2

In [26]:
## getting information from tensors    ######   Day 2   ######

In [27]:

rank_4_tensor = tf.zeros(shape=(2,4,5,3))
rank_4_tensor

<tf.Tensor: shape=(2, 4, 5, 3), dtype=float32, numpy=
array([[[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]]], dtype=f

In [28]:
rank_4_tensor.ndim, rank_4_tensor.shape, tf.size(rank_4_tensor)

(4, TensorShape([2, 4, 5, 3]), <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [29]:
# get various attribute of our tensor

print("Datatype of every element:", rank_4_tensor.dtype)
print("Number of dimension, rank:", rank_4_tensor.ndim)
print("Shape of tensor:", rank_4_tensor.shape)
print("Elements along the 0 axis:", rank_4_tensor.shape[0])
print("Elements along the last axis",rank_4_tensor.shape[-1])
print("Total no of elements in out tensor:", tf.size(rank_4_tensor).numpy())
                                                        


Datatype of every element: <dtype: 'float32'>
Number of dimension, rank: 4
Shape of tensor: (2, 4, 5, 3)
Elements along the 0 axis: 2
Elements along the last axis 3
Total no of elements in out tensor: 120


In [30]:
# list operations
some_list =[1,2,3,4]
some_list[:2] # first two elements of the some_list

[1, 2]

In [31]:
# get first two elements of
rank_4_tensor[:2,:2,:2,:3]

<tf.Tensor: shape=(2, 2, 2, 3), dtype=float32, numpy=
array([[[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]]], dtype=float32)>

In [32]:
# get the first element of each dimension except the last one
rank_4_tensor[:1,:1,:1,]

<tf.Tensor: shape=(1, 1, 1, 3), dtype=float32, numpy=array([[[[0., 0., 0.]]]], dtype=float32)>

In [33]:
# get the only last one
rank_4_tensor[:1,:1,:1,]

<tf.Tensor: shape=(1, 1, 1, 3), dtype=float32, numpy=array([[[[0., 0., 0.]]]], dtype=float32)>

In [34]:
# get the first element of each dimension except the second last one
rank_4_tensor[:1,:1,:,:1]

<tf.Tensor: shape=(1, 1, 5, 1), dtype=float32, numpy=
array([[[[0.],
         [0.],
         [0.],
         [0.],
         [0.]]]], dtype=float32)>

In [35]:
rank_2_tensor = tf.constant([[1,2],
                            [4,6]])
rank_2_tensor, rank_2_tensor.shape, rank_2_tensor.ndim

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[1, 2],
        [4, 6]])>,
 TensorShape([2, 2]),
 2)

In [36]:
some_list[-1] # last element of the some

4

In [37]:
rank_2_tensor[:,1] # get the last item of each raw

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([2, 6])>

## Day 3
    Let do this this as consecutive third day

In [38]:
# create arank two tensort (2 dim)

rank_2_tensor = tf.constant(
    [[10,7]
    ,[3,4]]
)
rank_2_tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]])>

In [39]:
#get the last item in tensor
rank_2_tensor[:,-1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 4])>

In [40]:
# add another dimension
rank_3_tensor = rank_2_tensor[..., tf.newaxis]

In [41]:
rank_3_tensor.ndim

3

In [42]:
# alternative to tf.newaxis  expand dimension of a tensor
new_rank_tensor = tf.expand_dims(rank_2_tensor,-1)
new_rank_tensor


<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]])>

### Manipluating tensors
** Basic Operation ** 

`+`,`-`,`*`,`/`

In [43]:
tensor = tf.constant(
    [[10,7],
    [8,6]]
)

tensor + 10  # original tensor vales are not changed

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [18, 16]])>

In [44]:
tensor # original tensor remain same
# can use tensorflow built in function too
tf.multiply(tensor,10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 80,  60]])>

** Matrix Multiplication **

In [45]:
print(tensor)

tf.Tensor(
[[10  7]
 [ 8  6]], shape=(2, 2), dtype=int32)


In [46]:
tf.matmul(tensor,tensor)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[156, 112],
       [128,  92]])>

In [47]:
x = tf.constant(
    [
        [1,2],
        [3,4],
        [6,8]
    ]
)

y = tf.constant(
    [
        [4,8],
        [2,6],
        [9,19]
    ]
)

x,y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [6, 8]])>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 4,  8],
        [ 2,  6],
        [ 9, 19]])>)

In [48]:
# matrix multiplycation using python operator
# first we have to reshape the matrix

x @ tf.reshape(y, shape=(2,3))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 16,  26,  40],
       [ 36,  60,  82],
       [ 72, 120, 164]])>

In [49]:
# using built in fuction
tf.matmul(x, tf.reshape(y, shape=(2,3)))


<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 16,  26,  40],
       [ 36,  60,  82],
       [ 72, 120, 164]])>

In [50]:
# transpose of a matrix
tf.matmul(x, tf.transpose(y))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 20,  14,  47],
       [ 44,  30, 103],
       [ 88,  60, 206]])>

** The dot product ** 
* tf.tensordot()


## Change the data type of tensor

**Day - keep growing baby**

*Change the data type of tensor*  💀 

In [51]:
B = tf.constant([1,2,3,4,5])
B.dtype

tf.int32

In [52]:
D = tf.cast(B, dtype = tf.float16)
D

<tf.Tensor: shape=(5,), dtype=float16, numpy=array([1., 2., 3., 4., 5.], dtype=float16)>

**Aggregating tensors**

condensing them from myltiple values down to a smaller amount of values

In [53]:
# get the absolute value of tensor
D = tf.constant([-1, 2,3,-25])

tf.abs(D) 

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([ 1,  2,  3, 25])>

Following forms of aggregation
* Get the maximum
* Get the minimum
* Mean of a tensor
* sum of a tensor

In [54]:
# random tensor with values between 0 and 100 of size 50

E = tf.constant(np.random.randint(0,100, size=50))
E

<tf.Tensor: shape=(50,), dtype=int32, numpy=
array([61, 85, 96, 51, 16, 26, 22, 42, 44, 72, 53, 30, 56, 99,  7, 45, 60,
       16, 65, 91, 76, 55, 96, 58, 14, 89, 93, 21, 56, 71, 61, 60, 21, 35,
       39, 68, 79, 42, 59,  9, 43, 44, 76, 32,  1, 82, 91,  2, 98, 19])>

In [55]:
# fine minimum
tf.reduce_min(E)

<tf.Tensor: shape=(), dtype=int32, numpy=1>

In [56]:
np.min(E)

1

In [57]:
#find the maximum
tf.reduce_max(E)

<tf.Tensor: shape=(), dtype=int32, numpy=99>

In [58]:
# find the mean
tf.reduce_mean(E)

<tf.Tensor: shape=(), dtype=int32, numpy=52>

In [59]:
# find the sum 
tf.reduce_sum(E)

<tf.Tensor: shape=(), dtype=int32, numpy=2627>

## 🛠 *Exe - Find the variance and std*

In [60]:
# tensor flow probability package - not found
# using tf.math.reduce_std

tf.math.reduce_std(tf.cast(E, dtype=tf.float32))



<tf.Tensor: shape=(), dtype=float32, numpy=27.980858>

In [61]:
tf.math.reduce_variance(tf.cast(E, dtype = tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=782.92847>

## Find the positional maximum and minimum 

In [62]:
# create new tensor with tf.random

F = tf.random.uniform(shape=[60])
F

<tf.Tensor: shape=(60,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043,
       0.6073899 , 0.46523476, 0.97803545, 0.7223145 , 0.32347047,
       0.82577336, 0.4976915 , 0.19483674, 0.7588748 , 0.3380444 ],
      dtype=float32)>

In [63]:
# find the positional maximum, place of maximum value
tf.argmax(F)

<tf.Tensor: shape=(), dtype=int64, numpy=52>

In [64]:
# value of maximum
F[tf.argmax(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.97803545>

In [65]:
# find the maximum value
tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=float32, numpy=0.97803545>

In [66]:
# positional minimum
tf.argmin(F)

<tf.Tensor: shape=(), dtype=int64, numpy=16>

In [67]:
# find the minimum value

F[tf.argmin(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.009463668>

## Squeesing a tensor (remove all 1 dimensions)

In [68]:
tf.random.set_seed(42)
G = tf.constant( tf.random.uniform(shape=[50]), shape = [1,1,1,1,50])
G

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
           0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
           0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
           0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
           0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
           0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
           0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
           0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
           0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
           0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]]]]],
      dtype=float32)>

In [69]:
G_squeezed = tf.squeeze(G)
G_squeezed, G_squeezed.shape , G_squeezed.ndim

(<tf.Tensor: shape=(50,), dtype=float32, numpy=
 array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
        0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
        0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
        0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
        0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
        0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
        0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
        0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
        0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
        0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
       dtype=float32)>,
 TensorShape([50]),
 1)

## One hot encoding

In [70]:
# create a some list
some_list = [0,1,2,3,4]

# one hot encoded tensor
tf.one_hot(some_list, depth =4)

<tf.Tensor: shape=(5, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]], dtype=float32)>

In [71]:
# specify custom values for one hot encoding
tf.one_hot(some_list, depth = 4, on_value = 'deep learning', off_value = 'painting')

<tf.Tensor: shape=(5, 4), dtype=string, numpy=
array([[b'deep learning', b'painting', b'painting', b'painting'],
       [b'painting', b'deep learning', b'painting', b'painting'],
       [b'painting', b'painting', b'deep learning', b'painting'],
       [b'painting', b'painting', b'painting', b'deep learning'],
       [b'painting', b'painting', b'painting', b'painting']], dtype=object)>

## Squaring , log, square root

In [72]:
# new tensor
H = tf.range(1,10)
H

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9])>

In [73]:
# squaring

tf.square(H)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81])>

In [74]:
# Find the square root
#tf.sqrt(H)   # this method is not working


In [75]:
tf.sqrt(tf.cast(H, dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([1.       , 1.4142135, 1.7320508, 2.       , 2.2360678, 2.4494896,
       2.6457512, 2.828427 , 3.       ], dtype=float32)>

In [76]:
# find the log
tf.math.log(tf.cast(H, dtype = tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>

## Tensors and Numpy

In [77]:
# create a tensor directly from a Nmupy array
J = tf.constant(np.array([3.,4.,5.]))
J, type(J)

(<tf.Tensor: shape=(3,), dtype=float64, numpy=array([3., 4., 5.])>,
 tensorflow.python.framework.ops.EagerTensor)

In [78]:
# Convert tensor into numpy array
np.array(J), type(np.array(J))

(array([3., 4., 5.]), numpy.ndarray)

In [79]:
# or we can use
J.numpy()

array([3., 4., 5.])

In [80]:
# indexing
J.numpy()[0]

3.0

## Building Neural Networks in Tensorflow